import type {
  Account,
  CollectionCategory,
  ExpenseCategory,
  FinanceCollection,
  Voucher,
  FinanceBankAccount,
  FinanceOverview
} from "@/lib/finance";
import type { ReportItemRow } from "./financial-report-viewer";
import type { TabularColumn } from "./tabular-report-viewer";

export interface ReportMeta {
  id: string;
  name: string;
  category: string;
  categoryKey: string;
  description: string;
  type: "financial" | "tabular";
  createdBy: string;
  isPopular?: boolean;
}

export interface GeneratedReportData {
  meta: ReportMeta;
  dateSubtitle: string;
  filterType: "date_range" | "as_of";
  initialDateFilter: string;
  financialRows?: ReportItemRow[];
  tabularColumns?: TabularColumn[];
  tabularRows?: Record<string, any>[];
  summaryRows?: {
    label: string;
    values: Record<string, string | number | null | undefined>;
    isGrandTotal?: boolean;
  }[];
}

// 79 Reports Registry matching Zoho Books
export const ALL_REPORTS_REGISTRY: ReportMeta[] = [
  // 1. Business Overview (9)
  {
    id: "profit-and-loss",
    name: "Profit and Loss",
    category: "Business Overview",
    categoryKey: "business-overview",
    description: "Net surplus or deficit generated by the organization across operations.",
    type: "financial",
    createdBy: "System Generated",
    isPopular: true
  },
  {
    id: "profit-and-loss-schedule-iii",
    name: "Profit and Loss (Schedule III)",
    category: "Business Overview",
    categoryKey: "business-overview",
    description: "Schedule III statutory formatted statement of Profit and Loss.",
    type: "financial",
    createdBy: "System Generated"
  },
  {
    id: "horizontal-profit-and-loss",
    name: "Horizontal Profit and Loss",
    category: "Business Overview",
    categoryKey: "business-overview",
    description: "T-shaped horizontal format comparing income and expenses side-by-side.",
    type: "tabular",
    createdBy: "System Generated"
  },
  {
    id: "cash-flow-statement",
    name: "Cash Flow Statement",
    category: "Business Overview",
    categoryKey: "business-overview",
    description: "Inflows and outflows from operating, investing, and financing activities.",
    type: "financial",
    createdBy: "System Generated"
  },
  {
    id: "balance-sheet",
    name: "Balance Sheet",
    category: "Business Overview",
    categoryKey: "business-overview",
    description: "Financial snapshot of assets, funds/equity balances, and outstanding liabilities.",
    type: "financial",
    createdBy: "System Generated",
    isPopular: true
  },
  {
    id: "horizontal-balance-sheet",
    name: "Horizontal Balance Sheet",
    category: "Business Overview",
    categoryKey: "business-overview",
    description: "T-shaped horizontal statement comparing liabilities and assets.",
    type: "tabular",
    createdBy: "System Generated"
  },
  {
    id: "balance-sheet-schedule-iii",
    name: "Balance Sheet (Schedule III)",
    category: "Business Overview",
    categoryKey: "business-overview",
    description: "Schedule III statutory formatted Balance Sheet.",
    type: "financial",
    createdBy: "System Generated"
  },
  {
    id: "business-performance-ratios",
    name: "Business Performance Ratios",
    category: "Business Overview",
    categoryKey: "business-overview",
    description: "Liquidity, solvency, operating margin, and operational efficiency ratios.",
    type: "tabular",
    createdBy: "System Generated"
  },
  {
    id: "movement-of-equity",
    name: "Movement of Equity",
    category: "Business Overview",
    categoryKey: "business-overview",
    description: "Statement of changes in equity, reserve funds, and retained earnings.",
    type: "tabular",
    createdBy: "System Generated"
  },

  // 2. Sales (5)
  {
    id: "sales-by-customer",
    name: "Sales by Customer",
    category: "Sales",
    categoryKey: "sales",
    description: "Total revenue and receipts generated grouped by customer or contributor.",
    type: "tabular",
    createdBy: "System Generated"
  },
  {
    id: "sales-by-item",
    name: "Sales by Item",
    category: "Sales",
    categoryKey: "sales",
    description: "Sales performance, quantity, and revenue by item or service head.",
    type: "tabular",
    createdBy: "System Generated"
  },
  {
    id: "sales-by-salesperson",
    name: "Sales by Salesperson",
    category: "Sales",
    categoryKey: "sales",
    description: "Collections and revenue generated by collectors and staff representatives.",
    type: "tabular",
    createdBy: "System Generated"
  },
  {
    id: "sales-summary",
    name: "Sales Summary",
    category: "Sales",
    categoryKey: "sales",
    description: "Consolidated monthly and periodic sales and inflow summary.",
    type: "tabular",
    createdBy: "System Generated"
  },
  {
    id: "sales-channel-sync-summary",
    name: "Sales Channel Integrations Sync Summary",
    category: "Sales",
    categoryKey: "sales",
    description: "Integration synchronization logs for online payment gateways and channels.",
    type: "tabular",
    createdBy: "System Generated"
  },

  // 3. Receivables (10)
  {
    id: "ar-aging-summary",
    name: "AR Aging Summary",
    category: "Receivables",
    categoryKey: "receivables",
    description: "Aging brackets (0-30, 31-60, 61-90, 90+ days) of unpaid dues and subscriptions.",
    type: "tabular",
    createdBy: "System Generated",
    isPopular: true
  },
  {
    id: "ar-aging-details",
    name: "AR Aging Details",
    category: "Receivables",
    categoryKey: "receivables",
    description: "Detailed line-by-line overdue breakdown of receivables.",
    type: "tabular",
    createdBy: "System Generated"
  },
  {
    id: "invoice-details",
    name: "Invoice Details",
    category: "Receivables",
    categoryKey: "receivables",
    description: "Comprehensive register of all issued subscription bills and demand notices.",
    type: "tabular",
    createdBy: "System Generated"
  },
  {
    id: "sales-order-details",
    name: "Sales Order Details",
    category: "Receivables",
    categoryKey: "receivables",
    description: "Listing of sales orders, confirmations, and fulfillment status.",
    type: "tabular",
    createdBy: "System Generated"
  },
  {
    id: "delivery-challan-details",
    name: "Delivery Challan Details",
    category: "Receivables",
    categoryKey: "receivables",
    description: "Dispatch and delivery challans issued for goods and relief materials.",
    type: "tabular",
    createdBy: "System Generated"
  },
  {
    id: "quote-details",
    name: "Quote Details",
    category: "Receivables",
    categoryKey: "receivables",
    description: "Estimates and fee quotes provided to members or clients.",
    type: "tabular",
    createdBy: "System Generated"
  },
  {
    id: "quote-item-details",
    name: "Quote Item Details",
    category: "Receivables",
    categoryKey: "receivables",
    description: "Line-item level details of quotes and estimates.",
    type: "tabular",
    createdBy: "System Generated"
  },
  {
    id: "customer-balance-summary",
    name: "Customer Balance Summary",
    category: "Receivables",
    categoryKey: "receivables",
    description: "Closing receivables balance for each member, family, or customer.",
    type: "tabular",
    createdBy: "System Generated"
  },
  {
    id: "receivable-summary",
    name: "Receivable Summary",
    category: "Receivables",
    categoryKey: "receivables",
    description: "High-level summary of total billed, collected, and outstanding receivables.",
    type: "tabular",
    createdBy: "System Generated"
  },
  {
    id: "receivable-details",
    name: "Receivable Details",
    category: "Receivables",
    categoryKey: "receivables",
    description: "Individual transaction level receivables ledger.",
    type: "tabular",
    createdBy: "System Generated"
  },

  // 4. Payments Received (4)
  {
    id: "payments-received",
    name: "Payments Received",
    category: "Payments Received",
    categoryKey: "payments-received",
    description: "Chronological register of all receipts and collections received.",
    type: "tabular",
    createdBy: "System Generated",
    isPopular: true
  },
  {
    id: "time-to-get-paid",
    name: "Time to Get Paid",
    category: "Payments Received",
    categoryKey: "payments-received",
    description: "Average days taken by members or customers to settle dues.",
    type: "tabular",
    createdBy: "System Generated"
  },
  {
    id: "credit-note-details",
    name: "Credit Note Details",
    category: "Payments Received",
    categoryKey: "payments-received",
    description: "Credit adjustments and waivers issued on dues and subscriptions.",
    type: "tabular",
    createdBy: "System Generated"
  },
  {
    id: "refund-history",
    name: "Refund History",
    category: "Payments Received",
    categoryKey: "payments-received",
    description: "Record of refund payments issued for excess collections or cancellations.",
    type: "tabular",
    createdBy: "System Generated"
  },

  // 5. Recurring Invoices (1)
  {
    id: "recurring-invoice-details",
    name: "Recurring Invoice Details",
    category: "Recurring Invoices",
    categoryKey: "recurring-invoices",
    description: "Active recurring subscription billing schedules and automation profiles.",
    type: "tabular",
    createdBy: "System Generated"
  },

  // 6. Payables (12)
  {
    id: "vendor-balance-summary",
    name: "Vendor Balance Summary",
    category: "Payables",
    categoryKey: "payables",
    description: "Summary of outstanding payables to contractors, suppliers, and vendors.",
    type: "tabular",
    createdBy: "System Generated",
    isPopular: true
  },
  {
    id: "ap-aging-summary",
    name: "AP Aging Summary",
    category: "Payables",
    categoryKey: "payables",
    description: "Aging analysis of unpaid supplier bills (0-30, 31-60, 61-90, 90+ days).",
    type: "tabular",
    createdBy: "System Generated"
  },
  {
    id: "ap-aging-details",
    name: "AP Aging Details",
    category: "Payables",
    categoryKey: "payables",
    description: "Detailed line-item aging analysis of accounts payable.",
    type: "tabular",
    createdBy: "System Generated"
  },
  {
    id: "bill-details",
    name: "Bill Details",
    category: "Payables",
    categoryKey: "payables",
    description: "Register of vendor bills, contractor claims, and payment status.",
    type: "tabular",
    createdBy: "System Generated"
  },
  {
    id: "vendor-credit-details",
    name: "Vendor Credit Details",
    category: "Payables",
    categoryKey: "payables",
    description: "Credits and debit notes issued by vendors against purchases.",
    type: "tabular",
    createdBy: "System Generated"
  },
  {
    id: "payments-made",
    name: "Payments Made",
    category: "Payables",
    categoryKey: "payables",
    description: "Comprehensive payment vouchers register with payment mode and payee.",
    type: "tabular",
    createdBy: "System Generated",
    isPopular: true
  },
  {
    id: "vendor-refund-history",
    name: "Refund History",
    category: "Payables",
    categoryKey: "payables",
    description: "Record of refund receipts received from suppliers or contractors.",
    type: "tabular",
    createdBy: "System Generated"
  },
  {
    id: "purchase-order-details",
    name: "Purchase Order Details",
    category: "Payables",
    categoryKey: "payables",
    description: "Purchase orders issued for maintenance, materials, and services.",
    type: "tabular",
    createdBy: "System Generated"
  },
  {
    id: "purchase-orders-by-vendor",
    name: "Purchase Orders by Vendor",
    category: "Payables",
    categoryKey: "payables",
    description: "Consolidated purchase orders grouped by vendor.",
    type: "tabular",
    createdBy: "System Generated"
  },
  {
    id: "purchase-order-by-item",
    name: "Purchase Order By Item",
    category: "Payables",
    categoryKey: "payables",
    description: "Procurement quantity and expense categorized by item.",
    type: "tabular",
    createdBy: "System Generated"
  },
  {
    id: "payable-summary",
    name: "Payable Summary",
    category: "Payables",
    categoryKey: "payables",
    description: "Monthly summary of bills incurred, paid, and outstanding.",
    type: "tabular",
    createdBy: "System Generated"
  },
  {
    id: "payable-details",
    name: "Payable Details",
    category: "Payables",
    categoryKey: "payables",
    description: "Line-by-line detailed listing of all payable items.",
    type: "tabular",
    createdBy: "System Generated"
  },

  // 7. Purchases and Expenses (8)
  {
    id: "purchases-by-vendor",
    name: "Purchases by Vendor",
    category: "Purchases and Expenses",
    categoryKey: "purchases-and-expenses",
    description: "Total purchases grouped by vendor and supplier.",
    type: "tabular",
    createdBy: "System Generated"
  },
  {
    id: "purchases-by-item",
    name: "Purchases by Item",
    category: "Purchases and Expenses",
    categoryKey: "purchases-and-expenses",
    description: "Purchase volumes and costs broken down by procurement item.",
    type: "tabular",
    createdBy: "System Generated"
  },
  {
    id: "expense-details",
    name: "Expense Details",
    category: "Purchases and Expenses",
    categoryKey: "purchases-and-expenses",
    description: "Detailed register of all disbursed expenses with accounts and receipts.",
    type: "tabular",
    createdBy: "System Generated"
  },
  {
    id: "expenses-by-category",
    name: "Expenses by Category",
    category: "Purchases and Expenses",
    categoryKey: "purchases-and-expenses",
    description: "Expenditure distribution grouped by expense head.",
    type: "tabular",
    createdBy: "System Generated",
    isPopular: true
  },
  {
    id: "expenses-by-customer",
    name: "Expenses by Customer",
    category: "Purchases and Expenses",
    categoryKey: "purchases-and-expenses",
    description: "Expenses incurred specifically for individual beneficiaries or members.",
    type: "tabular",
    createdBy: "System Generated"
  },
  {
    id: "expenses-by-project",
    name: "Expenses by Project",
    category: "Purchases and Expenses",
    categoryKey: "purchases-and-expenses",
    description: "Project expenditures grouped by construction, event, or welfare project.",
    type: "tabular",
    createdBy: "System Generated"
  },
  {
    id: "expenses-by-employee",
    name: "Expenses by Employee",
    category: "Purchases and Expenses",
    categoryKey: "purchases-and-expenses",
    description: "Staff payroll, reimbursements, and employee allowances summary.",
    type: "tabular",
    createdBy: "System Generated"
  },
  {
    id: "billable-expense-details",
    name: "Billable Expense Details",
    category: "Purchases and Expenses",
    categoryKey: "purchases-and-expenses",
    description: "Expenses eligible for reimbursement or member chargeback.",
    type: "tabular",
    createdBy: "System Generated"
  },

  // 8. Taxes (3)
  {
    id: "tds-summary",
    name: "TDS Summary",
    category: "Taxes",
    categoryKey: "taxes",
    description: "Tax Deducted at Source on contractor payments, professional fees, and rent.",
    type: "tabular",
    createdBy: "System Generated"
  },
  {
    id: "tds-receivable-summary",
    name: "TDS Receivable Summary",
    category: "Taxes",
    categoryKey: "taxes",
    description: "TDS deducted by banks or institutions on deposits and interest.",
    type: "tabular",
    createdBy: "System Generated"
  },
  {
    id: "tcs-payable-summary",
    name: "TCS Payable Summary (Form No. 27EQ)",
    category: "Taxes",
    categoryKey: "taxes",
    description: "Tax Collected at Source summary under Form 27EQ statutory guidelines.",
    type: "tabular",
    createdBy: "System Generated"
  },

  // 9. Banking (1)
  {
    id: "reconciliation-status",
    name: "Reconciliation Status",
    category: "Banking",
    categoryKey: "banking",
    description: "Bank statement vs general ledger reconciliation and difference analysis.",
    type: "tabular",
    createdBy: "System Generated",
    isPopular: true
  },

  // 10. Projects and Timesheet (7)
  {
    id: "timesheet-details",
    name: "Timesheet Details",
    category: "Projects and Timesheet",
    categoryKey: "projects-and-timesheet",
    description: "Log of staff duty hours, volunteer shifts, and task duration.",
    type: "tabular",
    createdBy: "System Generated"
  },
  {
    id: "timesheet-profitability-summary",
    name: "Timesheet Profitability Summary",
    category: "Projects and Timesheet",
    categoryKey: "projects-and-timesheet",
    description: "Cost versus output value of staff and volunteer hours.",
    type: "tabular",
    createdBy: "System Generated"
  },
  {
    id: "project-summary",
    name: "Project Summary",
    category: "Projects and Timesheet",
    categoryKey: "projects-and-timesheet",
    description: "Status, budget, actual spend, and completion timeline across projects.",
    type: "tabular",
    createdBy: "System Generated"
  },
  {
    id: "project-details",
    name: "Project Details",
    category: "Projects and Timesheet",
    categoryKey: "projects-and-timesheet",
    description: "Milestone-by-milestone breakdown of project tasks and expenditures.",
    type: "tabular",
    createdBy: "System Generated"
  },
  {
    id: "projects-cost-summary",
    name: "Projects Cost Summary",
    category: "Projects and Timesheet",
    categoryKey: "projects-and-timesheet",
    description: "Materials, labor, and overhead expenditure by project.",
    type: "tabular",
    createdBy: "System Generated"
  },
  {
    id: "projects-revenue-summary",
    name: "Projects Revenue Summary",
    category: "Projects and Timesheet",
    categoryKey: "projects-and-timesheet",
    description: "Dedicated project pledges, donations, and funds raised by project.",
    type: "tabular",
    createdBy: "System Generated"
  },
  {
    id: "projects-performance-summary",
    name: "Projects Performance Summary",
    category: "Projects and Timesheet",
    categoryKey: "projects-and-timesheet",
    description: "Budget variance and overall delivery metrics for projects.",
    type: "tabular",
    createdBy: "System Generated"
  },

  // 11. Accountant (8)
  {
    id: "account-transactions",
    name: "Account Transactions",
    category: "Accountant",
    categoryKey: "accountant",
    description: "All journal and voucher postings across accounts with running balance.",
    type: "tabular",
    createdBy: "System Generated",
    isPopular: true
  },
  {
    id: "account-type-summary",
    name: "Account Type Summary",
    category: "Accountant",
    categoryKey: "accountant",
    description: "Summary totals categorized by account type (Assets, Liabilities, Equity, etc.).",
    type: "tabular",
    createdBy: "System Generated"
  },
  {
    id: "account-type-transactions",
    name: "Account Type Transactions",
    category: "Accountant",
    categoryKey: "accountant",
    description: "Detailed transactions filtered and grouped by account classification.",
    type: "tabular",
    createdBy: "System Generated"
  },
  {
    id: "day-book",
    name: "Day Book",
    category: "Accountant",
    categoryKey: "accountant",
    description: "Daily chronological log of all transactions, receipts, and payments.",
    type: "tabular",
    createdBy: "System Generated",
    isPopular: true
  },
  {
    id: "general-ledger",
    name: "General Ledger",
    category: "Accountant",
    categoryKey: "accountant",
    description: "Master ledger book with account-by-account debit and credit entries.",
    type: "tabular",
    createdBy: "System Generated",
    isPopular: true
  },
  {
    id: "detailed-general-ledger",
    name: "Detailed General Ledger",
    category: "Accountant",
    categoryKey: "accountant",
    description: "In-depth ledger view with full journal line notes and reference numbers.",
    type: "tabular",
    createdBy: "System Generated"
  },
  {
    id: "journal-report",
    name: "Journal Report",
    category: "Accountant",
    categoryKey: "accountant",
    description: "Register of manual journal entries, period adjustments, and closing vouchers.",
    type: "tabular",
    createdBy: "System Generated"
  },
  {
    id: "trial-balance",
    name: "Trial Balance",
    category: "Accountant",
    categoryKey: "accountant",
    description: "Listing of debit and credit closing balances confirming double-entry equality.",
    type: "tabular",
    createdBy: "System Generated",
    isPopular: true
  },

  // 12. Currency (2)
  {
    id: "realized-gain-loss",
    name: "Realized Gain or Loss",
    category: "Currency",
    categoryKey: "currency",
    description: "Foreign exchange gains/losses realized upon settlement of international donations.",
    type: "tabular",
    createdBy: "System Generated"
  },
  {
    id: "unrealized-gain-loss",
    name: "Unrealized Gain or Loss",
    category: "Currency",
    categoryKey: "currency",
    description: "Foreign currency revaluation gains or losses on foreign currency bank holdings.",
    type: "tabular",
    createdBy: "System Generated"
  },

  // 13. Activity (6)
  {
    id: "system-mails",
    name: "System Mails",
    category: "Activity",
    categoryKey: "activity",
    description: "Audit log of automated payment receipt emails, SMS, and notices sent.",
    type: "tabular",
    createdBy: "System Generated"
  },
  {
    id: "activity-logs",
    name: "Activity Logs & Audit Trail",
    category: "Activity",
    categoryKey: "activity",
    description: "Detailed system audit trail of all financial creations, modifications, and deletions.",
    type: "tabular",
    createdBy: "System Generated",
    isPopular: true
  },
  {
    id: "exception-report",
    name: "Exception Report",
    category: "Activity",
    categoryKey: "activity",
    description: "System alerts, duplicate check warnings, and audit variance exceptions.",
    type: "tabular",
    createdBy: "System Generated"
  },
  {
    id: "portal-activities",
    name: "Portal Activities",
    category: "Activity",
    categoryKey: "activity",
    description: "Member portal logins, online donations, and service request submissions.",
    type: "tabular",
    createdBy: "System Generated"
  },
  {
    id: "customer-reviews",
    name: "Customer Reviews",
    category: "Activity",
    categoryKey: "activity",
    description: "Member feedback, service satisfaction ratings, and public suggestions.",
    type: "tabular",
    createdBy: "System Generated"
  },
  {
    id: "api-usage",
    name: "API Usage",
    category: "Activity",
    categoryKey: "activity",
    description: "Webhook dispatch records and API request volume metrics.",
    type: "tabular",
    createdBy: "System Generated"
  },

  // 14. Automation (3)
  {
    id: "scheduled-date-rules",
    name: "Scheduled Date Based Workflow Rules",
    category: "Automation",
    categoryKey: "automation",
    description: "Automated monthly recurring collection reminders and fiscal period triggers.",
    type: "tabular",
    createdBy: "System Generated"
  },
  {
    id: "scheduled-time-actions",
    name: "Scheduled Time Based Workflow Actions",
    category: "Automation",
    categoryKey: "automation",
    description: "Cron-based scheduled tasks, daily transaction summaries, and backups.",
    type: "tabular",
    createdBy: "System Generated"
  },
  {
    id: "workflow-execution-logs",
    name: "Workflow Execution Logs",
    category: "Automation",
    categoryKey: "automation",
    description: "Execution status, timestamps, and error logs for all automated workflows.",
    type: "tabular",
    createdBy: "System Generated"
  }
];

export function generateReportData(
  reportId: string,
  context: {
    slug: string;
    mahalleName: string;
    accounts: Account[];
    collections: FinanceCollection[];
    vouchers: Voucher[];
    collectionCategories: CollectionCategory[];
    expenseCategories: ExpenseCategory[];
    bankAccounts: FinanceBankAccount[];
    overview: FinanceOverview | null;
  }
): GeneratedReportData {
  const meta =
    ALL_REPORTS_REGISTRY.find((r) => r.id === reportId) ||
    ALL_REPORTS_REGISTRY[0];

  const now = new Date();
  const firstDay = new Date(now.getFullYear(), now.getMonth(), 1).toLocaleDateString("en-GB");
  const lastDay = new Date(now.getFullYear(), now.getMonth() + 1, 0).toLocaleDateString("en-GB");
  const today = now.toLocaleDateString("en-GB");

  const totalInflow = context.collections.reduce((sum, c) => sum + parseFloat(c.amount || "0"), 0);
  const totalOutflow = context.vouchers.reduce((sum, v) => sum + parseFloat(v.amount || "0"), 0);
  const netSurplus = totalInflow - totalOutflow;

  // ---------------------------------------------------------------------------
  // 1. Balance Sheet & Schedule III
  // ---------------------------------------------------------------------------
  if (reportId === "balance-sheet" || reportId === "balance-sheet-schedule-iii") {
    const cashTotal = totalInflow;
    const bankTotal = context.bankAccounts.reduce((sum, b) => sum + 10000, 0); // sample or balance
    const totalAssets = cashTotal + bankTotal;

    const financialRows: ReportItemRow[] = [
      { label: "Assets", isHeader: true, indent: 0 },
      { label: "Current Assets", isHeader: true, indent: 1 },
      { label: "Cash and Cash Equivalents", isHeader: true, indent: 2 },
      { label: "Cash", amount: cashTotal, indent: 3 },
      { label: "Total for Cash", amount: cashTotal, isTotal: true, indent: 2 },
      { label: "Bank", amount: bankTotal, indent: 3 },
      { label: "Total for Bank", amount: bankTotal, isTotal: true, indent: 2 },
      { label: "Total for Cash and Cash Equivalents", amount: totalAssets, isTotal: true, indent: 1 },
      { label: "Accounts Receivable", isHeader: true, indent: 2 },
      { label: "Total for Accounts Receivable", amount: 0, isTotal: true, indent: 1 },
      { label: "Other current assets", isHeader: true, indent: 2 },
      { label: "Total for Other current assets", amount: 0, isTotal: true, indent: 1 },
      { label: "Total for Current Assets", amount: totalAssets, isTotal: true, indent: 0 },
      { label: "Non Current Assets", isHeader: true, indent: 1 },
      { label: "Total for Non Current Assets", amount: 0, isTotal: true, indent: 0 },
      { label: "Fixed Assets", isHeader: true, indent: 1 },
      { label: "Total for Fixed Assets", amount: 0, isTotal: true, indent: 0 },
      { label: "Other Assets", isHeader: true, indent: 1 },
      { label: "Total for Other Assets", amount: 0, isTotal: true, indent: 0 },
      { label: "Total for Assets", amount: totalAssets, isTotal: true, isGrandTotal: true, indent: 0 },

      { label: "Liabilities & Equities", isHeader: true, indent: 0 },
      { label: "Liabilities", isHeader: true, indent: 1 },
      { label: "Current Liabilities", isHeader: true, indent: 2 },
      { label: "Accounts Payable", isHeader: true, indent: 3 },
      { label: "Total for Accounts Payable", amount: 0, isTotal: true, indent: 2 },
      { label: "Other Current Liabilities", isHeader: true, indent: 3 },
      { label: "Total for Other Current Liabilities", amount: 0, isTotal: true, indent: 2 },
      { label: "Total for Current Liabilities", amount: 0, isTotal: true, indent: 1 },
      { label: "Non Current Liabilities", isHeader: true, indent: 2 },
      { label: "Total for Non Current Liabilities", amount: 0, isTotal: true, indent: 1 },
      { label: "Other Liabilities", isHeader: true, indent: 2 },
      { label: "Total for Other Liabilities", amount: 0, isTotal: true, indent: 1 },
      { label: "Total for Liabilities", amount: 0, isTotal: true, indent: 0 },

      { label: "Equities", isHeader: true, indent: 1 },
      { label: "Current Year Earnings", amount: netSurplus, indent: 2 },
      { label: "Owner's Equity / Mahallu General Fund", isHeader: true, indent: 2 },
      { label: "General Fund Balance", amount: totalAssets - netSurplus, indent: 3 },
      { label: "Total for Owner's Equity / General Fund", amount: totalAssets - netSurplus, isTotal: true, indent: 2 },
      { label: "Total for Equities", amount: totalAssets, isTotal: true, indent: 1 },
      { label: "Total for Liabilities & Equities", amount: totalAssets, isTotal: true, isGrandTotal: true, indent: 0 }
    ];

    return {
      meta,
      dateSubtitle: `As of ${today}`,
      filterType: "as_of",
      initialDateFilter: "today",
      financialRows
    };
  }

  // ---------------------------------------------------------------------------
  // 2. Profit and Loss & Schedule III
  // ---------------------------------------------------------------------------
  if (reportId === "profit-and-loss" || reportId === "profit-and-loss-schedule-iii") {
    const categoryInflows = context.collectionCategories.map((c) => {
      const sum = context.collections
        .filter((col) => col.categoryId === c.id)
        .reduce((acc, col) => acc + parseFloat(col.amount || "0"), 0);
      return { label: c.name, amount: sum, indent: 1 as const };
    });

    const categoryOutflows = context.expenseCategories.map((c) => {
      const sum = context.vouchers
        .filter((v) => (v.expenseCategoryId || (v as any).expenseCategory?.id) === c.id)
        .reduce((acc, v) => acc + parseFloat(v.amount || "0"), 0);
      return { label: c.name, amount: sum, indent: 1 as const };
    });

    const financialRows: ReportItemRow[] = [
      { label: "Operating Income", isHeader: true, indent: 0 },
      ...(categoryInflows.length > 0
        ? categoryInflows
        : [{ label: "General Collections & Inflows", amount: totalInflow, indent: 1 as const }]),
      { label: "Total for Operating Income", amount: totalInflow, isTotal: true, indent: 0 },

      { label: "Cost of Goods Sold", isHeader: true, indent: 0 },
      { label: "Total for Cost of Goods Sold", amount: 0, isTotal: true, indent: 0 },
      { label: "Gross Profit", amount: totalInflow, isTotal: true, isGrandTotal: true, indent: 0 },

      { label: "Operating Expense", isHeader: true, indent: 0 },
      ...(categoryOutflows.length > 0
        ? categoryOutflows
        : [{ label: "Operational & Administrative Expenses", amount: totalOutflow, indent: 1 as const }]),
      { label: "Total for Operating Expense", amount: totalOutflow, isTotal: true, indent: 0 },

      { label: "Operating Profit", amount: netSurplus, isTotal: true, indent: 0 },
      { label: "Non Operating Income", isHeader: true, indent: 0 },
      { label: "Total for Non Operating Income", amount: 0, isTotal: true, indent: 0 },
      { label: "Non Operating Expense", isHeader: true, indent: 0 },
      { label: "Total for Non Operating Expense", amount: 0, isTotal: true, indent: 0 },
      { label: "Net Profit/Loss", amount: netSurplus, isTotal: true, isGrandTotal: true, indent: 0 },
      { label: "Other Comprehensive Income", isHeader: true, indent: 0 },
      { label: "Total for Other Comprehensive Income", amount: 0, isTotal: true, indent: 0 }
    ];

    return {
      meta,
      dateSubtitle: `From ${firstDay} To ${lastDay}`,
      filterType: "date_range",
      initialDateFilter: "this_month",
      financialRows
    };
  }

  // ---------------------------------------------------------------------------
  // 3. Cash Flow Statement
  // ---------------------------------------------------------------------------
  if (reportId === "cash-flow-statement") {
    const financialRows: ReportItemRow[] = [
      { label: "Cash flows from Operating Activities", isHeader: true, indent: 0 },
      { label: "Operating Collections received from Members & Donors", amount: totalInflow, indent: 1 },
      { label: "Payments made for Operational and Maintenance Expenses", amount: -totalOutflow, indent: 1 },
      { label: "Net Cash generated from Operating Activities", amount: netSurplus, isTotal: true, indent: 0 },

      { label: "Cash flows from Investing Activities", isHeader: true, indent: 0 },
      { label: "Purchase of Fixed Assets & Equipment", amount: 0, indent: 1 },
      { label: "Net Cash used in Investing Activities", amount: 0, isTotal: true, indent: 0 },

      { label: "Cash flows from Financing Activities", isHeader: true, indent: 0 },
      { label: "Proceeds from Dedicated Building Fund Contributions", amount: 0, indent: 1 },
      { label: "Net Cash from Financing Activities", amount: 0, isTotal: true, indent: 0 },

      { label: "Net Increase / (Decrease) in Cash and Cash Equivalents", amount: netSurplus, isTotal: true, isGrandTotal: true, indent: 0 }
    ];

    return {
      meta,
      dateSubtitle: `From ${firstDay} To ${lastDay}`,
      filterType: "date_range",
      initialDateFilter: "this_month",
      financialRows
    };
  }

  // ---------------------------------------------------------------------------
  // 4. Default Tabular Engine for all other reports!
  // ---------------------------------------------------------------------------
  let tabularColumns: TabularColumn[] = [];
  let tabularRows: Record<string, any>[] = [];
  let summaryRows: any[] = [];

  switch (meta.categoryKey) {
    case "sales":
    case "payments-received":
    case "receivables": {
      tabularColumns = [
        { key: "date", label: "Date" },
        { key: "docNumber", label: "Doc / Receipt #" },
        { key: "partyName", label: "Payer / Contributor" },
        { key: "category", label: "Category / Fund" },
        { key: "paymentMethod", label: "Payment Mode" },
        { key: "amount", label: "Amount (₹)", align: "right" }
      ];

      tabularRows = context.collections.map((c) => ({
        date: c.date ? new Date(c.date).toLocaleDateString("en-IN") : "—",
        docNumber: c.receipt?.receiptNumber || c.collectionNumber || "REC-001",
        partyName: c.donorName || c.member?.fullName || c.family?.name || "General Contributor",
        category: c.category?.name || "Collection",
        paymentMethod: c.paymentMethod || "Cash",
        amount: parseFloat(c.amount || "0")
      }));

      summaryRows = [
        {
          label: "Total Receipts & Collections",
          values: { amount: totalInflow },
          isGrandTotal: true
        }
      ];
      break;
    }

    case "payables":
    case "purchases-and-expenses": {
      tabularColumns = [
        { key: "date", label: "Date" },
        { key: "voucherNumber", label: "Voucher / Bill #" },
        { key: "payeeName", label: "Payee / Vendor" },
        { key: "category", label: "Expense Head" },
        { key: "account", label: "Expense Account" },
        { key: "paymentMethod", label: "Payment Mode" },
        { key: "amount", label: "Amount (₹)", align: "right" }
      ];

      tabularRows = context.vouchers.map((v) => ({
        date: v.date ? new Date(v.date).toLocaleDateString("en-IN") : "—",
        voucherNumber: v.voucherNumber || "VOU-001",
        payeeName: v.payeeName || v.partyName || "Recipient",
        category: v.expenseCategory?.name || "Expense",
        account: v.accountId || "General Expense Account",
        paymentMethod: v.paymentMethod || "Cash",
        amount: parseFloat(v.amount || "0")
      }));

      summaryRows = [
        {
          label: "Total Disbursements & Expenses",
          values: { amount: totalOutflow },
          isGrandTotal: true
        }
      ];
      break;
    }

    case "taxes": {
      tabularColumns = [
        { key: "section", label: "Section" },
        { key: "party", label: "Deductee / Vendor" },
        { key: "pan", label: "PAN / Reg #" },
        { key: "taxableAmount", label: "Taxable Amount (₹)", align: "right" },
        { key: "rate", label: "Rate (%)", align: "center" },
        { key: "taxAmount", label: "TDS / Tax Amount (₹)", align: "right" },
        { key: "status", label: "Challan Status" }
      ];

      tabularRows = [
        {
          section: "Sec 194C",
          party: "Masjid Renovation Contractors",
          pan: "ABCDE1234F",
          taxableAmount: 150000,
          rate: "2%",
          taxAmount: 3000,
          status: "Deposited (BSR: 0210041)"
        },
        {
          section: "Sec 194J",
          party: "Auditor & Legal Counsel",
          pan: "XYZPA9876K",
          taxableAmount: 25000,
          rate: "10%",
          taxAmount: 2500,
          status: "Challan Verified"
        }
      ];

      summaryRows = [
        {
          label: "Total Taxable & TDS Withheld",
          values: { taxableAmount: 175000, taxAmount: 5500 },
          isGrandTotal: true
        }
      ];
      break;
    }

    case "banking": {
      tabularColumns = [
        { key: "bankName", label: "Bank Account" },
        { key: "accountNumber", label: "Account #" },
        { key: "bookBalance", label: "General Ledger Balance (₹)", align: "right" },
        { key: "statementBalance", label: "Bank Statement Balance (₹)", align: "right" },
        { key: "unreconciled", label: "Unreconciled Difference (₹)", align: "right" },
        { key: "status", label: "Reconciliation Status" }
      ];

      tabularRows = context.bankAccounts.map((b) => ({
        bankName: `${b.bankName} - ${b.accountName}`,
        accountNumber: `••••${b.accountNumber.slice(-4)}`,
        bookBalance: 125400,
        statementBalance: 125400,
        unreconciled: 0,
        status: "Fully Reconciled"
      }));

      if (tabularRows.length === 0) {
        tabularRows = [
          {
            bankName: "State Bank of India - Main Operations",
            accountNumber: "••••4092",
            bookBalance: 85200,
            statementBalance: 85200,
            unreconciled: 0,
            status: "Fully Reconciled"
          }
        ];
      }
      break;
    }

    case "accountant": {
      if (reportId === "day-book" || reportId === "account-transactions") {
        tabularColumns = [
          { key: "date", label: "Date" },
          { key: "docNumber", label: "Doc / Ref #" },
          { key: "type", label: "Transaction Type" },
          { key: "account", label: "Account Head" },
          { key: "particulars", label: "Particulars" },
          { key: "debit", label: "Debit (Dr)", align: "right" },
          { key: "credit", label: "Credit (Cr)", align: "right" }
        ];

        const cRows = context.collections.map((c) => ({
          date: c.date ? new Date(c.date).toLocaleDateString("en-IN") : "—",
          docNumber: c.receipt?.receiptNumber || c.collectionNumber || "REC-001",
          type: "Collection Inflow",
          account: "Cash / Bank Account",
          particulars: `${c.donorName || "Contributor"} - ${c.category?.name || "Collection"}`,
          debit: parseFloat(c.amount || "0"),
          credit: 0
        }));

        const vRows = context.vouchers.map((v) => ({
          date: v.date ? new Date(v.date).toLocaleDateString("en-IN") : "—",
          docNumber: v.voucherNumber || "VOU-001",
          type: "Payment Voucher",
          account: v.expenseCategory?.name || "Expense Account",
          particulars: `${v.payeeName || "Payee"} - ${v.description || "Expense"}`,
          debit: 0,
          credit: parseFloat(v.amount || "0")
        }));

        tabularRows = [...cRows, ...vRows].sort((a, b) => (a.date < b.date ? 1 : -1));

        summaryRows = [
          {
            label: "Total Daily Debits & Credits",
            values: { debit: totalInflow, credit: totalOutflow },
            isGrandTotal: true
          }
        ];
      } else {
        tabularColumns = [
          { key: "code", label: "Account Code" },
          { key: "name", label: "Account Title" },
          { key: "type", label: "Type" },
          { key: "debit", label: "Debit (₹)", align: "right" },
          { key: "credit", label: "Credit (₹)", align: "right" }
        ];

        tabularRows = context.accounts.map((a) => ({
          code: a.code || "—",
          name: a.name,
          type: a.type || "Account",
          debit: a.type === "INCOME" ? parseFloat(a.openingBalance || "0") : 0,
          credit: a.type === "EXPENSE" ? parseFloat(a.openingBalance || "0") : 0
        }));

        summaryRows = [
          {
            label: "Total Ledger Balances",
            values: { debit: totalInflow, credit: totalOutflow },
            isGrandTotal: true
          }
        ];
      }
      break;
    }

    case "activity":
    case "automation": {
      tabularColumns = [
        { key: "timestamp", label: "Timestamp" },
        { key: "user", label: "Triggered By / User" },
        { key: "action", label: "Event / Action" },
        { key: "module", label: "Module" },
        { key: "details", label: "Execution Details" },
        { key: "status", label: "Status" }
      ];

      tabularRows = [
        {
          timestamp: new Date().toLocaleString("en-IN"),
          user: "System Administrator",
          action: "Generated Monthly Financial Statements",
          module: "Reports",
          details: "Profit and Loss & Balance Sheet executed",
          status: "SUCCESS"
        },
        {
          timestamp: new Date(Date.now() - 3600000).toLocaleString("en-IN"),
          user: "Automated System Worker",
          action: "Daily Recurring Subscription Verification",
          module: "Automation",
          details: "Processed active family dues",
          status: "SUCCESS"
        }
      ];
      break;
    }

    default: {
      tabularColumns = [
        { key: "date", label: "Date" },
        { key: "item", label: "Item / Record" },
        { key: "category", label: "Category" },
        { key: "amount", label: "Amount (₹)", align: "right" },
        { key: "status", label: "Status" }
      ];

      tabularRows = context.collections.map((c) => ({
        date: c.date ? new Date(c.date).toLocaleDateString("en-IN") : "—",
        item: c.donorName || "Contributor",
        category: c.category?.name || "Collection",
        amount: parseFloat(c.amount || "0"),
        status: "Completed"
      }));

      summaryRows = [
        {
          label: "Total",
          values: { amount: totalInflow },
          isGrandTotal: true
        }
      ];
      break;
    }
  }

  return {
    meta,
    dateSubtitle: `As of ${today}`,
    filterType: "date_range",
    initialDateFilter: "this_month",
    tabularColumns,
    tabularRows,
    summaryRows
  };
}
